name: scribblr
description: "Seonghwa Dorm."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
 
  intl: any
  cupertino_icons: ^1.0.8
  nb_utils: ^7.0.4
  google_fonts: ^6.2.1
  country_picker: ^2.0.26
  flag: ^7.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.1
  ionicons: ^0.2.2
  image_picker: ^1.1.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  shared_preferences: ^2.3.2



  provider: any
  get: ^4.7.2
  cached_network_image: ^3.4.1
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1
  file_picker: ^9.0.2
  awesome_notifications: ^0.10.0
  onesignal_flutter: ^5.3.0
dev_dependencies:
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/icons/
   - assets/lottie/
   - assets/authors/
   - assets/articles/
   - assets/icon.png
   - assets/default_user.png
   - assets/default_cover.jpg